config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#homepage'

  get 'help/mobile', to: 'pages#help'

  get 'plans/mobile-plans', to: 'plans#mobile'

  get 'plans/nbn', to: 'plans#nbn'

  get 'plans/data-plans', to: 'plans#data'

  get 'terms-policies/competition-promos', to: 'pages#competitions'

  #get 'pages/help', :to => 'pages#help' #pages controller help action

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def homepage
  end

  def help
    @name = 'Sophie' #checks this data before it goes to view
  end

  def competitions
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  def mobile
  end

  def nbn
  end

  def data
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/layouts/_jumbo.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <div class="row">
    <div class="col-8">
    <h1 class="display-4">win a Google Home, Chromecast Ultra and a year of nbn ™
    </h1>
    <p class="lead">Sign up to any nbn plan before 31 August to go into the draw. Plans start from $40 a month.
    </p>
    <a class="terms" href="/terms-policies/competition-promos" >T&C's apply</a>
    <p class="lead">
      <a class="btn btn-primary btn-lg" href="#" role="button">sign up</a>
    </div>
      <div class="d-flex align-items-end col-4">
        <img src="https://www.amaysim.com.au/sites/default/files/styles/retina_1x/public/2017-08/Header_Image-nbn-com-2.png?itok=_pwM8VHJ" alt="">
      </div>
    </p>
  </div>
</div>
</div>

app/views/layouts/_jumbo2.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <div class="row">
      <div class="col-2">
        <img src="https://www.amaysim.com.au/sites/default/files/cta/2017-07/website_award_2016-2017.png" alt="">
      </div>
      <div class="col-8">
        <h5>93% of our customers have recommended amaysim to their mates</h5>
        <p>NPS tracking survey of 2679 customers, May 2017</p>
      </div>
      <div class="col-2">
        <p class="lead">
          <a class="btn btn-primary btn-lg" href="#" role="button">compare plans</a>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-orange">
  <div class ="container">
  <a class="navbar-brand text-white" href="/">amaysim</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">plans
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="/plans/mobile-plans">mobile plans</a>
          <a class="dropdown-item" href="/plans/nbn">nbn plans</a>
          <a class="dropdown-item" href="/plans/data-plans">data plans</a>
        </div>
      </li>


      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspop="true" aria-expanded="false">about
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="#">who are we</a>
          <a class="dropdown-item" href="#">why amaysim</a>
          <a class="dropdown-item" href="#">check mobile network coverage</a>
          <a class="dropdown-item" href="#">find a store</a>
          <a class="dropdown-item" href="#">read our blog</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/help/mobile">help</a>
      </li>
    </ul>
  </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Amaysim</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- <a href="/help/mobile">Help</a> -->
    <!-- <%= link_to 'Help', help_mobile_path %> -->
    <!-- <%= link_to 'Help URL', help_mobile_url %> -->
<%= render 'layouts/nav' %>

  <!-- <div class="container"> -->
    <%= yield %>
  <!-- </div> -->
  </body>
</html>

app/views/pages/help.html.erb
<h1>Pages#help</h1>
<p>Find me in app/views/pages/help.html.erb</p>

<h1>

  <%= @name %>

</h1>

app/views/pages/homepage.html.erb
<%= render 'layouts/jumbo' %>
<div class="bg-white">
  <div class="container">
    <div class="row">
        <div class="col-1">
          <img src="https://www.amaysim.com.au/sites/default/files/2017-04/lock_dash_mint.svg" alt="">
        </div>
        <div class="col-3">
          <h6>no lock-in contracts</h6>
          <p>Freedom to switch your plan or cancel at anytime.</p>
        </div>
        <div class="col-1">
          <img src="https://www.amaysim.com.au/sites/default/files/2017-04/join_dash_mint.svg" alt="">
        </div>
        <div class="col-3">
          <h6>simple to join</h6>
          <p>Quick and easy online sign-up, we’ll take care of all the fiddly bits.</p>
        </div>
        <div class="col-1">
          <img src="https://www.amaysim.com.au/sites/default/files/2017-04/app_dash_mint.svg" alt="">
        </div>
        <div class="col-3">
          <h6>easy to manage</h6>
          <p>Download our app or manage your plans online.</p>
        </div>
      </div>
    </div>
</div>

<div class="card-container">
  <div class="card-deck">
    <div class="card">
      <div class="card-body card-one">
        <h4 class="card-title">sim-only mobile plans</h4>
          <p class="card-text">Unlimited standard talk &amp; text with heaps of data for use in Oz.</p>
        </div>
        <img class="card-img-top" src="https://www.amaysim.com.au/sites/default/files/styles/coloured_callout/public/cta/2017-05/mobile%20plans.png?itok=cW9n3w3K" alt="Card image cap">
        <div class="card-footer card-footer-1">
          <small class="text-muted"> <a href="/plans/mobile-plans" target="_blank">mobile plans</a></small>
        </div>
    </div>
    <div class="card">
      <div class="card-body card-two">
        <h4 class="card-title">nbn broadband plans</h4>
        <p class="card-text">Unlimited data with superfast speeds. No lock-in contracts.</p>
      </div>
      <img class="card-img-top" src="https://www.amaysim.com.au/sites/default/files/styles/coloured_callout/public/cta/2017-05/nbn.png?itok=HQEt97oW" alt="Card image cap">
      <div class="card-footer card-footer-2">
        <small class="text-muted"><a href="/plans/nbn" target="_blank">nbn plans</a></small>
      </div>
    </div>
    <div class="card">
      <div class="card-body card-three">
        <h4 class="card-title">data-only plans</h4>
        <p class="card-text">Mobile broadband for your tablets and devices, for use in Oz.</p>
      </div>
      <img class="card-img-top" src="https://www.amaysim.com.au/sites/default/files/styles/coloured_callout/public/cta/2017-05/data%20only.png?itok=p6sU-ykV" alt="Card image cap">
      <div class="card-footer card-footer-3">
        <small class="text-muted"><a href="/plans/data-plans" target="">data only</a></small>
      </div>
    </div>
  </div>
</div>


<%= render 'layouts/jumbo2' %>

<div class="bg-white">
  <div class="container">
    <div class="row">
      <div class="col-sm-9">
        <h2>what we've been up to</h2>
        <div class="row">
          <div class="col-7 w-75">
            <div class="card text-center">
              <div class="card-body">
                <h4 class="card-title">we've been named the best VNO</h4>
                <p class="card-text">Delivering on the promises that we made to Aussies 6 years ago.</p>
                <a href="#" class="btn btn-read">read all about it</a>
              </div>
            </div>
          </div>

          <div class="col-5 text-nowrap">
            <h5 class="col-title">What a two year mobile phone contract will really cost you</h5>
            <p class="tech-talk">14 Sep 2016 in <a href="#">Tech Talk</a></p>
            <h5 class="col-title">Check out our new and improved Help section</h5>
            <p class="help-sect">14 Sep 2016 in <a href="#">Plans and Services</a></p>
            <h5 class="col-title">AS YOU GO credit now lasts for 365 days</h5>
            <p class="plans-serv">16 Sep 2016 in <a href="#">Plans and Services</a></p>
          </div>
      </div>
    </div>
  </div>
</div>
</div> <!--bg-white-end -->

<!--bg white begin-->
<div class="bg-white">
  <div class="container">
    <div class="row">
      <div class="col-sm-9">
        <h2>already with amaysim?</h2>
    </div>

    </div>























  </div><!--container-end-->
</div><!--bg white end-->

app/views/plans/data.html.erb
<h1>data plans</h1>

app/views/plans/mobile.html.erb
<!--mobile.html.erb -->

<h1>You've made it to /plans/mobile-plans</h1>

app/views/plans/nbn.html.erb
<h1>Welcome to nbn</h1>